### ISSUE TITLE
Ukládání do GITu

### ISSUE THREAD

**Issue by stlmik** [jiridudekusy/uuDockitHelper#1]
Trochu mě trápí, že dockit zatím nemá historii verzí - co třeba ukládat při stisku "save page" to samé i do GITu?

**Comment by ghost99cze** [comment]
Podle mých informací v další verzi DocKitu bude i verzování - snad koncem února. Tak je otázka, zda to sem aktuálně přidávat.
Je otázka, zda tam bude i nějaké porovnání verzí. Na to by možná bylo lepší to držet v GITu v Markdownu.

**Comment by jiridudekusy** [comment]
Pokud bude mit docktit podporu verzi a bude mit i command na stazeni hitoricky verze, tak je zbytecne to ukladat nekam jinam. Potom staci jen stahnout 2 historicke verze, prevest do MD a udelat srovnani pres nejaky JS diff tool.

**Comment by stlmik** [comment]
ok, tak počkejme na podporu verzí v dockitu
