### ISSUE TITLE
Second "Save Page" will fail on ""uu-app-objectstore/invalidRevision"

### ISSUE THREAD

**Issue by PetrHavelka** [jiridudekusy/uuDockitHelper#5]
In case of second save it will fail on:

`Page "uuCmdGatewayWebServicesCmdPut" cannot be saved. Error : "{"status":400,"data":{"uuAppErrorMap":{"uu-bookkit-main/updatePage/pageDaoUpdateByCodeFailed":{"id":"xxx","timestamp":"2019-01-07T11:16:57.355Z","type":"error","message":"Update page by page DAO updateByCode failed.","paramMap":{"cause":"Used value of revision attribute is lower than its value in database."},"cause":{"uuAppErrorMap":{"uu-app-objectstore/invalidRevision":{"id":"xxx","timestamp":"2019-01-07T11:16:57.355Z","type":"error","message":"Used value of revision attribute is lower than its value in database."}}}}}},"error":{"id":"xxx","timestamp":"2019-01-07T11:16:57.355Z","type":"error","message":"Update page by page DAO updateByCode failed.","paramMap":{"cause":"Used value of revision attribute is lower than its value in database."},"cause":{"uuAppErrorMap":{"uu-app-objectstore/invalidRevision":{"id":"xxx","timestamp":"2019-01-07T11:16:57.355Z","type":"error","message":"Used value of revision attribute is lower than its value in database."}}},"code":"uu-bookkit-main/updatePage/pageDaoUpdateByCodeFailed"}}"`

**Comment by jiridudekusy** [comment]
Fixed in version 0.5.1
